DROP TABLE IF EXISTS `aijiacms_newhouse_6`;
CREATE TABLE `aijiacms_newhouse_6` (
  `itemid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `catid` varchar(30) NOT NULL DEFAULT '0',
  `mycatid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `typeid` smallint(2) unsigned NOT NULL DEFAULT '0',
  `areaid` smallint(6) unsigned NOT NULL DEFAULT '0',
  `level` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `elite` tinyint(1) NOT NULL DEFAULT '0',
  `title` varchar(100) NOT NULL DEFAULT '',
  `style` varchar(50) NOT NULL DEFAULT '',
  `fee` float NOT NULL DEFAULT '0',
  `introduce` varchar(255) NOT NULL DEFAULT '',
  `price` decimal(10,0) unsigned NOT NULL,
  `days` smallint(3) unsigned NOT NULL DEFAULT '0',
  `tag` varchar(100) NOT NULL DEFAULT '',
  `keyword` varchar(255) NOT NULL DEFAULT '',
  `pptword` varchar(255) NOT NULL DEFAULT '',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `thumb` varchar(255) NOT NULL DEFAULT '',
  `thumb1` varchar(255) NOT NULL DEFAULT '',
  `thumb2` varchar(255) NOT NULL DEFAULT '',
  `username` varchar(30) NOT NULL DEFAULT '',
  `groupid` smallint(4) unsigned NOT NULL DEFAULT '0',
  `company` varchar(100) NOT NULL DEFAULT '',
  `vip` smallint(2) unsigned NOT NULL DEFAULT '0',
  `validated` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `truename` varchar(30) NOT NULL DEFAULT '',
  `telephone` varchar(50) NOT NULL DEFAULT '',
  `mobile` varchar(50) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(50) NOT NULL DEFAULT '',
  `msn` varchar(50) NOT NULL DEFAULT '',
  `qq` varchar(20) NOT NULL DEFAULT '',
  `ali` varchar(30) NOT NULL DEFAULT '',
  `skype` varchar(30) NOT NULL DEFAULT '',
  `totime` int(10) unsigned NOT NULL DEFAULT '0',
  `editor` varchar(30) NOT NULL DEFAULT '',
  `edittime` int(10) unsigned NOT NULL DEFAULT '0',
  `editdate` date NOT NULL DEFAULT '0000-00-00',
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  `adddate` date NOT NULL DEFAULT '0000-00-00',
  `ip` varchar(50) NOT NULL DEFAULT '',
  `template` varchar(30) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `linkurl` varchar(255) NOT NULL DEFAULT '',
  `filepath` varchar(255) NOT NULL DEFAULT '',
  `note` varchar(255) NOT NULL DEFAULT '',
  `letter` varchar(10) NOT NULL DEFAULT '' COMMENT '字母',
  `map` varchar(255) NOT NULL DEFAULT '' COMMENT '地图',
  `tedian` varchar(255) NOT NULL DEFAULT '' COMMENT '特点',
  `selltime` varchar(20) NOT NULL COMMENT '开盘时间',
  `completion` varchar(20) NOT NULL COMMENT '交房时间',
  `lp_type` varchar(20) NOT NULL DEFAULT '' COMMENT '物业类型',
  `lp_year` int(10) NOT NULL COMMENT '产权年限',
  `lp_company` varchar(30) NOT NULL DEFAULT '' COMMENT '物业公司',
  `lp_costs` float(10,2) NOT NULL COMMENT '物业费',
  `lp_totalarea` int(20) NOT NULL COMMENT '规划面积',
  `lp_area` int(10) DEFAULT NULL COMMENT '建筑面积',
  `lp_number` int(10) NOT NULL COMMENT '规划户数',
  `lp_car` int(10) DEFAULT NULL COMMENT '车位数',
  `lp_volume` float(10,2) DEFAULT NULL COMMENT '容积率',
  `lp_green` int(10) DEFAULT NULL COMMENT '绿化率',
  `lp_bus` varchar(50) DEFAULT '' COMMENT '公车',
  `lp_edu` varchar(50) DEFAULT '' COMMENT '教育',
  `lp_hospital` varchar(50) DEFAULT NULL COMMENT '医院',
  `lp_bank` varchar(50) DEFAULT '' COMMENT '银行',
  `lineprice` varchar(50) NOT NULL DEFAULT '' COMMENT '曲线价格',
  `linedate` varchar(100) NOT NULL DEFAULT '' COMMENT '曲线日期',
  `sell_address` varchar(50) DEFAULT NULL,
  `buildtype` varchar(255) NOT NULL,
  `kfs` varchar(255) NOT NULL,
  `lp_dianping` varchar(255) DEFAULT NULL,
  `isnew` int(4) DEFAULT '0',
  `fitment` varchar(255) NOT NULL,
  `bbsurl` varchar(255) NOT NULL,
  `lpts` varchar(255) NOT NULL,
  `range` varchar(80) NOT NULL,
  `pinyin` varchar(80) DEFAULT NULL,
  `isfx` int(4) DEFAULT '0',
  `yongjin` varchar(80) NOT NULL,
  PRIMARY KEY (`itemid`),
  KEY `username` (`username`),
  KEY `editdate` (`editdate`,`vip`,`edittime`),
  KEY `edittime` (`edittime`),
  KEY `catid` (`catid`),
  KEY `mycatid` (`mycatid`),
  KEY `areaid` (`areaid`)
) TYPE=MyISAM COMMENT='新房';

DROP TABLE IF EXISTS `aijiacms_newhouse_search_6`;
CREATE TABLE `aijiacms_newhouse_search_6` (
  `itemid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `catid` int(10) unsigned NOT NULL DEFAULT '0',
  `areaid` smallint(6) unsigned NOT NULL DEFAULT '0',
  `content` text NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `sorttime` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemid`),
  KEY `catid` (`catid`)
) TYPE=MyISAM COMMENT='新房搜索';


DROP TABLE IF EXISTS `aijiacms_newhouse_data_6`;
CREATE TABLE `aijiacms_newhouse_data_6` (
  `itemid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `content` mediumtext NOT NULL,
  PRIMARY KEY (`itemid`)
) TYPE=MyISAM COMMENT='新房内容';